HIGH_PRIORITY = 'High Priority'
HIGH_PRIORITY_SHORT = 'High'
NORMAL_PRIORITY = 'Normal Priority'
NORMAL_PRIORITY_SHORT = 'Normal'
LOW_PRIORITY = 'Low Priority'
LOW_PRIORITY_SHORT = 'Low'
PRIORITIES = (
    (HIGH_PRIORITY_SHORT, HIGH_PRIORITY),
    (NORMAL_PRIORITY_SHORT, NORMAL_PRIORITY),
    (LOW_PRIORITY_SHORT, LOW_PRIORITY),
)
